title:             Janshair Khan
email:             kjanshair@gmail.com
# description:       A Blog Theme by Start Bootstrap
author:            Janshair Khan
# baseurl:           "/"
cdnurl:   "https://kjanshair.blob.core.windows.comnet"
url:               "http://blog.kjanshair.com"
permalink: /:year/:month/:day/:title/

# Social Profiles
twitter_username:  kjanshair
github_username:   kjanshair
linkedin_username: kjanshair
yahoo_username: kjanshair@yahoo.com

# Build settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM

paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
